import { Assets } from 'pixi.js';

/**
 * Loads the MSDF font atlas generated by msdf-bmfont-xml.
 * Pixi v8 detects the distanceField type from the .fnt descriptor automatically
 * (fieldType="msdf" in the XML) and registers the font under the face name
 * declared in the .fnt info block (currently "Arial" / "plant-label").
 *
 * Must be awaited before any BitmapText is created that references this font.
 */
export async function loadMsdfFont(): Promise<void> {
  await Assets.load('/fonts/plant-label.fnt');
}
